# -*- coding: utf-8 -*-
"""IRIS flower classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17erktvk81p2EQ6b-GfMePx7rbAnmUj9F

Importing all the dependencies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""importign dataset and visualization"""

#reading csv file and viewing random 5 rows
data = pd.read_csv('/content/IRIS.csv')
data.sample(5)

#checking the mean and total count of each type of specie in dataset
data.describe()

#checking data types of each specie and the number of non-null values and memory usage.
data.info()

#checking the name of columns in the dataset
data.columns

#check if there's any null value on the dataset
data.isnull().sum()

#splittign the dataset into x and y
x = data[['sepal_length','sepal_width','petal_length','petal_width']]
y = data[['species']]

#shape means that we have 150 lines and 4 columns
x.shape

#shape means that we have 150 rows and 1 column
y.shape

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

#to see if the splitting has done or not
len(x_train)

model = LogisticRegression()
model.fit(x_train,y_train)

prediction = model.predict(x_test)

prediction

prediction = prediction.reshape(-1, 1)
score = pd.DataFrame(prediction)
score.columns=['Predictions']
y_test_values = y_test.values
score['Actual'] = y_test_values

score.head()

print(accuracy_score(y_test,prediction)*100,'%')

